### PR TITLE
 Prevent token&auction address to be used in `bid()`

### PR DESCRIPTION
**Pull request by loredanacirstea**
Closes https://github.com/raiden-network/raiden-token/issues/91

Token and auction contract addresses should not be used as receivers of tokens.

### CODE REVIEW

**Comment by LefterisJP** [comment]
test

**Comment by LefterisJP** [comment]
needs rebase, right?

**Comment by LefterisJP** [comment]
Hmmm seems like something went wrong with your rebase? You have 6 commits in the PR, 2 of them duplicated.

**Comment by loredanacirstea** [comment]
Yes, nevermind opened https://github.com/raiden-network/raiden-token/pull/92 instead of this one.

**Pull request closed without merging**
